services:
  - type: web
    name: spam-ensemble-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn ensemble_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
